### ISSUE TITLE
Compile for 4.9-4.11 issues

### ISSUE THREAD

**Issue by jonathancumming** [Zinglish/Defragr#4]
Defragr.h needs this line changed:
#include "Engineminimal.h"
to
#include "Engine.h"

Also CMDSCALE can be removed as it is not used and abs causes compile errors in 4.10.

:+1:

**Comment by Zinglish** [comment]
What's the difference between minimal and normal includes? Is there a huge difference?

As for CMDSCALE; I haven't done refactoring of the code for an incredibly long time now (over 2 months I guess?).

Thanks for the pointers :)

**Comment by ianahl** [comment]
The project could not be compiled. Would you like to open it in Visual Studio?

Running C:/Program Files/Epic Games/4.9/Engine/Binaries/DotNET/UnrealBuildTool.exe Defragr Development Win64 -project="C:/Users/Ian/Documents/Unreal Projects/Defragr-master 4.9 - 4/Defragr.uproject" -rocket -editorrecompile -progress -noubtmakefiles
@progress push 5%
Parsing headers for DefragrEditor
  Running UnrealHeaderTool "C:/Users/Ian/Documents/Unreal Projects/Defragr-master 4.9 - 4/Defragr.uproject" "C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Intermediate\Build\Win64\DefragrEditor\Development\UnrealHeaderTool.manifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -rocket -installed
Reflection code generated for DefragrEditor in 15,9625912 seconds
@progress pop
Performing 19 actions (4 in parallel)
[2/19] Resource ModuleVersionResource.rc.inl
[3/19] Resource PCLaunch.rc
PCH.Defragr.h.cpp
WeaponPickup.cpp
Weapon.cpp
DefragrPlayer.cpp
DefragrPlayerMoveComponent.cpp
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.cpp(237) : error C2065: 'JumpSoundCue' : undeclared identifier
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.cpp(242) : error C2065: 'TeleportSoundCue' : undeclared identifier
Pickup.cpp
DefragrPlayerCollisionComponent.cpp
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Defragr.generated.cpp
DefragrHUD.cpp
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
TeleportVolume.cpp
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Intermediate\Build\Win64\UE4Editor\Inc\Defragr\Defragr.generated.cpp(819) : error C2039: 'TeleportSoundCue' : is not a member of 'ADefragrPlayer'
        C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(18) : see declaration of 'ADefragrPlayer'
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Intermediate\Build\Win64\UE4Editor\Inc\Defragr\Defragr.generated.cpp(819) : error C2664: 'UObjectProperty::UObjectProperty(const UObjectProperty &)' : cannot convert argument 1 from 'FObjectInitializer' to 'ECppProperty'
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Intermediate\Build\Win64\UE4Editor\Inc\Defragr\Defragr.generated.cpp(820) : error C2039: 'HardLandingSoundCue' : is not a member of 'ADefragrPlayer'
        C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(18) : see declaration of 'ADefragrPlayer'
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Intermediate\Build\Win64\UE4Editor\Inc\Defragr\Defragr.generated.cpp(820) : error C2664: 'UObjectProperty::UObjectProperty(const UObjectProperty &)' : cannot convert argument 1 from 'FObjectInitializer' to 'ECppProperty'
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Intermediate\Build\Win64\UE4Editor\Inc\Defragr\Defragr.generated.cpp(821) : error C2039: 'JumpSoundCue' : is not a member of 'ADefragrPlayer'
        C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Source\Defragr\DefragrPlayer.h(18) : see declaration of 'ADefragrPlayer'
C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Intermediate\Build\Win64\UE4Editor\Inc\Defragr\Defragr.generated.cpp(821) : error C2664: 'UObjectProperty::UObjectProperty(const UObjectProperty &)' : cannot convert argument 1 from 'FObjectInitializer' to 'ECppProperty'
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
JumpPadVolume.cpp
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Checkpoint.cpp
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
DefragrGameMode.cpp
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Projectile.cpp
TeleportTarget.cpp
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(79) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(82) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C2143: syntax error : missing ';' before '*'
c:\users\ian\documents\unreal projects\defragr-master 4.9 - 4\source\defragr\DefragrPlayer.h(85) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Defragr.cpp
-------- End Detailed Actions Stats -----------------------------------------------------------
ERROR: UBT ERROR: Failed to produce item: C:\Users\Ian\Documents\Unreal Projects\Defragr-master 4.9 - 4\Binaries\Win64\UE4Editor-Defragr.dll
Total build time: 116,17 seconds

Getting this error when compiling, im not a c++ coder so i don't really know whats wrong! :/
